let vetor = [1, 2, 3, 4, 5]
console.log(vetor)

vetor.push(7)
console.log(vetor)
vetor.push(8)
console.log(vetor)
vetor.push(9)
console.log(vetor)
console.log('-----')
vetor.pop()
console.log(vetor)
vetor.pop()
vetor.pop()
console.log(vetor)
console.table(vetor)